// An interesting function for the sake of it :skull:. via vim macros.
bool is_even_naive(int x) {
    switch (x)
    {
    case 0:
        return true;
    case 1:
        return false;
    case 2:
        return true;
    case 3:
        return false;
    case 4:
        return true;
    case 5:
        return false;
    case 6:
        return true;
    case 7:
        return false;
    case 8:
        return true;
    case 9:
        return false;
    case 10:
        return true;
    case 11:
        return false;
    case 12:
        return true;
    case 13:
        return false;
    case 14:
        return true;
    case 15:
        return false;
    case 16:
        return true;
    case 17:
        return false;
    case 18:
        return true;
    case 19:
        return false;
    case 20:
        return true;
    case 21:
        return false;
    case 22:
        return true;
    case 23:
        return false;
    case 24:
        return true;
    case 25:
        return false;
    case 26:
        return true;
    case 27:
        return false;
    case 28:
        return true;
    case 29:
        return false;
    case 30:
        return true;
    case 31:
        return false;
    case 32:
        return true;
    case 33:
        return false;
    case 34:
        return true;
    case 35:
        return false;
    case 36:
        return true;
    case 37:
        return false;
    case 38:
        return true;
    case 39:
        return false;
    case 40:
        return true;
    case 41:
        return false;
    case 42:
        return true;
    case 43:
        return false;
    case 44:
        return true;
    case 45:
        return false;
    case 46:
        return true;
    case 47:
        return false;
    case 48:
        return true;
    case 49:
        return false;
    case 50:
        return true;
    case 51:
        return false;
    case 52:
        return true;
    case 53:
        return false;
    case 54:
        return true;
    case 55:
        return false;
    case 56:
        return true;
    case 57:
        return false;
    case 58:
        return true;
    case 59:
        return false;
    case 60:
        return true;
    case 61:
        return false;
    case 62:
        return true;
    case 63:
        return false;
    case 64:
        return true;
    case 65:
        return false;
    case 66:
        return true;
    case 67:
        return false;
    case 68:
        return true;
    case 69:
        return false;
    case 70:
        return true;
    case 71:
        return false;
    case 72:
        return true;
    case 73:
        return false;
    case 74:
        return true;
    case 75:
        return false;
    case 76:
        return true;
    case 77:
        return false;
    case 78:
        return true;
    case 79:
        return false;
    case 80:
        return true;
    case 81:
        return false;
    case 82:
        return true;
    case 83:
        return false;
    case 84:
        return true;
    case 85:
        return false;
    case 86:
        return true;
    case 87:
        return false;
    case 88:
        return true;
    case 89:
        return false;
    case 90:
        return true;
    case 91:
        return false;
    case 92:
        return true;
    case 93:
        return false;
    case 94:
        return true;
    case 95:
        return false;
    case 96:
        return true;
    case 97:
        return false;
    case 98:
        return true;
    case 99:
        return false;
    case 100:
        return true;
    case 101:
        return false;
    case 102:
        return true;
    case 103:
        return false;
    case 104:
        return true;
    case 105:
        return false;
    case 106:
        return true;
    case 107:
        return false;
    case 108:
        return true;
    case 109:
        return false;
    case 110:
        return true;
    case 111:
        return false;
    case 112:
        return true;
    case 113:
        return false;
    case 114:
        return true;
    case 115:
        return false;
    case 116:
        return true;
    case 117:
        return false;
    case 118:
        return true;
    case 119:
        return false;
    case 120:
        return true;
    case 121:
        return false;
    case 122:
        return true;
    case 123:
        return false;
    case 124:
        return true;
    case 125:
        return false;
    case 126:
        return true;
    case 127:
        return false;
    case 128:
        return true;
    case 129:
        return false;
    case 130:
        return true;
    case 131:
        return false;
    case 132:
        return true;
    case 133:
        return false;
    case 134:
        return true;
    case 135:
        return false;
    case 136:
        return true;
    case 137:
        return false;
    case 138:
        return true;
    case 139:
        return false;
    case 140:
        return true;
    case 141:
        return false;
    case 142:
        return true;
    case 143:
        return false;
    case 144:
        return true;
    case 145:
        return false;
    case 146:
        return true;
    case 147:
        return false;
    case 148:
        return true;
    case 149:
        return false;
    case 150:
        return true;
    case 151:
        return false;
    case 152:
        return true;
    case 153:
        return false;
    case 154:
        return true;
    case 155:
        return false;
    case 156:
        return true;
    case 157:
        return false;
    case 158:
        return true;
    case 159:
        return false;
    case 160:
        return true;
    case 161:
        return false;
    case 162:
        return true;
    case 163:
        return false;
    case 164:
        return true;
    case 165:
        return false;
    case 166:
        return true;
    case 167:
        return false;
    case 168:
        return true;
    case 169:
        return false;
    case 170:
        return true;
    case 171:
        return false;
    case 172:
        return true;
    case 173:
        return false;
    case 174:
        return true;
    case 175:
        return false;
    case 176:
        return true;
    case 177:
        return false;
    case 178:
        return true;
    case 179:
        return false;
    case 180:
        return true;
    case 181:
        return false;
    case 182:
        return true;
    case 183:
        return false;
    case 184:
        return true;
    case 185:
        return false;
    case 186:
        return true;
    case 187:
        return false;
    case 188:
        return true;
    case 189:
        return false;
    case 190:
        return true;
    case 191:
        return false;
    case 192:
        return true;
    case 193:
        return false;
    case 194:
        return true;
    case 195:
        return false;
    case 196:
        return true;
    case 197:
        return false;
    case 198:
        return true;
    case 199:
        return false;
    case 200:
        return true;
    case 201:
        return false;
    case 202:
        return true;
    case 203:
        return false;
    case 204:
        return true;
    case 205:
        return false;
    case 206:
        return true;
    case 207:
        return false;
    case 208:
        return true;
    case 209:
        return false;
    case 210:
        return true;
    case 211:
        return false;
    case 212:
        return true;
    case 213:
        return false;
    case 214:
        return true;
    case 215:
        return false;
    case 216:
        return true;
    case 217:
        return false;
    case 218:
        return true;
    case 219:
        return false;
    case 220:
        return true;
    case 221:
        return false;
    case 222:
        return true;
    case 223:
        return false;
    case 224:
        return true;
    case 225:
        return false;
    case 226:
        return true;
    case 227:
        return false;
    case 228:
        return true;
    case 229:
        return false;
    case 230:
        return true;
    case 231:
        return false;
    case 232:
        return true;
    case 233:
        return false;
    case 234:
        return true;
    case 235:
        return false;
    case 236:
        return true;
    case 237:
        return false;
    case 238:
        return true;
    case 239:
        return false;
    case 240:
        return true;
    case 241:
        return false;
    case 242:
        return true;
    case 243:
        return false;
    case 244:
        return true;
    case 245:
        return false;
    case 246:
        return true;
    case 247:
        return false;
    case 248:
        return true;
    case 249:
        return false;
    case 250:
        return true;
    case 251:
        return false;
    case 252:
        return true;
    case 253:
        return false;
    case 254:
        return true;
    case 255:
        return false;
    case 256:
        return true;
    case 257:
        return false;
    case 258:
        return true;
    case 259:
        return false;
    case 260:
        return true;
    case 261:
        return false;
    case 262:
        return true;
    case 263:
        return false;
    case 264:
        return true;
    case 265:
        return false;
    case 266:
        return true;
    case 267:
        return false;
    case 268:
        return true;
    case 269:
        return false;
    case 270:
        return true;
    case 271:
        return false;
    case 272:
        return true;
    case 273:
        return false;
    case 274:
        return true;
    case 275:
        return false;
    case 276:
        return true;
    case 277:
        return false;
    case 278:
        return true;
    case 279:
        return false;
    case 280:
        return true;
    case 281:
        return false;
    case 282:
        return true;
    case 283:
        return false;
    case 284:
        return true;
    case 285:
        return false;
    case 286:
        return true;
    case 287:
        return false;
    case 288:
        return true;
    case 289:
        return false;
    case 290:
        return true;
    case 291:
        return false;
    case 292:
        return true;
    case 293:
        return false;
    case 294:
        return true;
    case 295:
        return false;
    case 296:
        return true;
    case 297:
        return false;
    case 298:
        return true;
    case 299:
        return false;
    case 300:
        return true;
    case 301:
        return false;
    case 302:
        return true;
    case 303:
        return false;
    case 304:
        return true;
    case 305:
        return false;
    case 306:
        return true;
    case 307:
        return false;
    case 308:
        return true;
    case 309:
        return false;
    case 310:
        return true;
    case 311:
        return false;
    case 312:
        return true;
    case 313:
        return false;
    case 314:
        return true;
    case 315:
        return false;
    case 316:
        return true;
    case 317:
        return false;
    case 318:
        return true;
    case 319:
        return false;
    case 320:
        return true;
    case 321:
        return false;
    case 322:
        return true;
    case 323:
        return false;
    case 324:
        return true;
    case 325:
        return false;
    case 326:
        return true;
    case 327:
        return false;
    case 328:
        return true;
    case 329:
        return false;
    case 330:
        return true;
    case 331:
        return false;
    case 332:
        return true;
    case 333:
        return false;
    case 334:
        return true;
    case 335:
        return false;
    case 336:
        return true;
    case 337:
        return false;
    case 338:
        return true;
    case 339:
        return false;
    case 340:
        return true;
    case 341:
        return false;
    case 342:
        return true;
    case 343:
        return false;
    case 344:
        return true;
    case 345:
        return false;
    case 346:
        return true;
    case 347:
        return false;
    case 348:
        return true;
    case 349:
        return false;
    case 350:
        return true;
    case 351:
        return false;
    case 352:
        return true;
    case 353:
        return false;
    case 354:
        return true;
    case 355:
        return false;
    case 356:
        return true;
    case 357:
        return false;
    case 358:
        return true;
    case 359:
        return false;
    case 360:
        return true;
    case 361:
        return false;
    case 362:
        return true;
    case 363:
        return false;
    case 364:
        return true;
    case 365:
        return false;
    case 366:
        return true;
    case 367:
        return false;
    case 368:
        return true;
    case 369:
        return false;
    case 370:
        return true;
    case 371:
        return false;
    case 372:
        return true;
    case 373:
        return false;
    case 374:
        return true;
    case 375:
        return false;
    case 376:
        return true;
    case 377:
        return false;
    case 378:
        return true;
    case 379:
        return false;
    case 380:
        return true;
    case 381:
        return false;
    case 382:
        return true;
    case 383:
        return false;
    case 384:
        return true;
    case 385:
        return false;
    case 386:
        return true;
    case 387:
        return false;
    case 388:
        return true;
    case 389:
        return false;
    case 390:
        return true;
    case 391:
        return false;
    case 392:
        return true;
    case 393:
        return false;
    case 394:
        return true;
    case 395:
        return false;
    case 396:
        return true;
    case 397:
        return false;
    case 398:
        return true;
    case 399:
        return false;
    case 400:
        return true;
    case 401:
        return false;
    case 402:
        return true;
    case 403:
        return false;
    case 404:
        return true;
    case 405:
        return false;
    case 406:
        return true;
    case 407:
        return false;
    case 408:
        return true;
    case 409:
        return false;
    case 410:
        return true;
    case 411:
        return false;
    case 412:
        return true;
    case 413:
        return false;
    case 414:
        return true;
    case 415:
        return false;
    case 416:
        return true;
    case 417:
        return false;
    case 418:
        return true;
    case 419:
        return false;
    case 420:
        return true;
    case 421:
        return false;
    case 422:
        return true;
    case 423:
        return false;
    case 424:
        return true;
    case 425:
        return false;
    case 426:
        return true;
    case 427:
        return false;
    case 428:
        return true;
    case 429:
        return false;
    case 430:
        return true;
    case 431:
        return false;
    case 432:
        return true;
    case 433:
        return false;
    case 434:
        return true;
    case 435:
        return false;
    case 436:
        return true;
    case 437:
        return false;
    case 438:
        return true;
    case 439:
        return false;
    case 440:
        return true;
    case 441:
        return false;
    case 442:
        return true;
    case 443:
        return false;
    case 444:
        return true;
    case 445:
        return false;
    case 446:
        return true;
    case 447:
        return false;
    case 448:
        return true;
    case 449:
        return false;
    case 450:
        return true;
    case 451:
        return false;
    case 452:
        return true;
    case 453:
        return false;
    case 454:
        return true;
    case 455:
        return false;
    case 456:
        return true;
    case 457:
        return false;
    case 458:
        return true;
    case 459:
        return false;
    case 460:
        return true;
    case 461:
        return false;
    case 462:
        return true;
    case 463:
        return false;
    case 464:
        return true;
    case 465:
        return false;
    case 466:
        return true;
    case 467:
        return false;
    case 468:
        return true;
    case 469:
        return false;
    case 470:
        return true;
    case 471:
        return false;
    case 472:
        return true;
    case 473:
        return false;
    case 474:
        return true;
    case 475:
        return false;
    case 476:
        return true;
    case 477:
        return false;
    case 478:
        return true;
    case 479:
        return false;
    case 480:
        return true;
    case 481:
        return false;
    case 482:
        return true;
    case 483:
        return false;
    case 484:
        return true;
    case 485:
        return false;
    case 486:
        return true;
    case 487:
        return false;
    case 488:
        return true;
    case 489:
        return false;
    case 490:
        return true;
    case 491:
        return false;
    case 492:
        return true;
    case 493:
        return false;
    case 494:
        return true;
    case 495:
        return false;
    case 496:
        return true;
    case 497:
        return false;
    case 498:
        return true;
    case 499:
        return false;
    case 500:
        return true;
    case 501:
        return false;
    case 502:
        return true;
    case 503:
        return false;
    case 504:
        return true;
    case 505:
        return false;
    case 506:
        return true;
    case 507:
        return false;
    case 508:
        return true;
    case 509:
        return false;
    case 510:
        return true;
    case 511:
        return false;
    case 512:
        return true;
    case 513:
        return false;
    case 514:
        return true;
    case 515:
        return false;
    case 516:
        return true;
    case 517:
        return false;
    case 518:
        return true;
    case 519:
        return false;
    case 520:
        return true;
    case 521:
        return false;
    case 522:
        return true;
    case 523:
        return false;
    case 524:
        return true;
    case 525:
        return false;
    case 526:
        return true;
    case 527:
        return false;
    case 528:
        return true;
    case 529:
        return false;
    case 530:
        return true;
    case 531:
        return false;
    case 532:
        return true;
    case 533:
        return false;
    case 534:
        return true;
    case 535:
        return false;
    case 536:
        return true;
    case 537:
        return false;
    case 538:
        return true;
    case 539:
        return false;
    case 540:
        return true;
    case 541:
        return false;
    case 542:
        return true;
    case 543:
        return false;
    case 544:
        return true;
    case 545:
        return false;
    case 546:
        return true;
    case 547:
        return false;
    case 548:
        return true;
    case 549:
        return false;
    case 550:
        return true;
    case 551:
        return false;
    case 552:
        return true;
    case 553:
        return false;
    case 554:
        return true;
    case 555:
        return false;
    case 556:
        return true;
    case 557:
        return false;
    case 558:
        return true;
    case 559:
        return false;
    case 560:
        return true;
    case 561:
        return false;
    case 562:
        return true;
    case 563:
        return false;
    case 564:
        return true;
    case 565:
        return false;
    case 566:
        return true;
    case 567:
        return false;
    case 568:
        return true;
    case 569:
        return false;
    case 570:
        return true;
    case 571:
        return false;
    case 572:
        return true;
    case 573:
        return false;
    case 574:
        return true;
    case 575:
        return false;
    case 576:
        return true;
    case 577:
        return false;
    case 578:
        return true;
    case 579:
        return false;
    case 580:
        return true;
    case 581:
        return false;
    case 582:
        return true;
    case 583:
        return false;
    case 584:
        return true;
    case 585:
        return false;
    case 586:
        return true;
    case 587:
        return false;
    case 588:
        return true;
    case 589:
        return false;
    case 590:
        return true;
    case 591:
        return false;
    case 592:
        return true;
    case 593:
        return false;
    case 594:
        return true;
    case 595:
        return false;
    case 596:
        return true;
    case 597:
        return false;
    case 598:
        return true;
    case 599:
        return false;
    case 600:
        return true;
    case 601:
        return false;
    case 602:
        return true;
    case 603:
        return false;
    case 604:
        return true;
    case 605:
        return false;
    case 606:
        return true;
    case 607:
        return false;
    case 608:
        return true;
    case 609:
        return false;
    case 610:
        return true;
    case 611:
        return false;
    case 612:
        return true;
    case 613:
        return false;
    case 614:
        return true;
    case 615:
        return false;
    case 616:
        return true;
    case 617:
        return false;
    case 618:
        return true;
    case 619:
        return false;
    case 620:
        return true;
    case 621:
        return false;
    case 622:
        return true;
    case 623:
        return false;
    case 624:
        return true;
    case 625:
        return false;
    case 626:
        return true;
    case 627:
        return false;
    case 628:
        return true;
    case 629:
        return false;
    case 630:
        return true;
    case 631:
        return false;
    case 632:
        return true;
    case 633:
        return false;
    case 634:
        return true;
    case 635:
        return false;
    case 636:
        return true;
    case 637:
        return false;
    case 638:
        return true;
    case 639:
        return false;
    case 640:
        return true;
    case 641:
        return false;
    case 642:
        return true;
    case 643:
        return false;
    case 644:
        return true;
    case 645:
        return false;
    case 646:
        return true;
    case 647:
        return false;
    case 648:
        return true;
    case 649:
        return false;
    case 650:
        return true;
    case 651:
        return false;
    case 652:
        return true;
    case 653:
        return false;
    case 654:
        return true;
    case 655:
        return false;
    case 656:
        return true;
    case 657:
        return false;
    case 658:
        return true;
    case 659:
        return false;
    case 660:
        return true;
    case 661:
        return false;
    case 662:
        return true;
    case 663:
        return false;
    case 664:
        return true;
    case 665:
        return false;
    case 666:
        return true;
    case 667:
        return false;
    case 668:
        return true;
    case 669:
        return false;
    case 670:
        return true;
    case 671:
        return false;
    case 672:
        return true;
    case 673:
        return false;
    case 674:
        return true;
    case 675:
        return false;
    case 676:
        return true;
    case 677:
        return false;
    case 678:
        return true;
    case 679:
        return false;
    case 680:
        return true;
    case 681:
        return false;
    case 682:
        return true;
    case 683:
        return false;
    case 684:
        return true;
    case 685:
        return false;
    case 686:
        return true;
    case 687:
        return false;
    case 688:
        return true;
    case 689:
        return false;
    case 690:
        return true;
    case 691:
        return false;
    case 692:
        return true;
    case 693:
        return false;
    case 694:
        return true;
    case 695:
        return false;
    case 696:
        return true;
    case 697:
        return false;
    case 698:
        return true;
    case 699:
        return false;
    case 700:
        return true;
    case 701:
        return false;
    case 702:
        return true;
    case 703:
        return false;
    case 704:
        return true;
    case 705:
        return false;
    case 706:
        return true;
    case 707:
        return false;
    case 708:
        return true;
    case 709:
        return false;
    case 710:
        return true;
    case 711:
        return false;
    case 712:
        return true;
    case 713:
        return false;
    case 714:
        return true;
    case 715:
        return false;
    case 716:
        return true;
    case 717:
        return false;
    case 718:
        return true;
    case 719:
        return false;
    case 720:
        return true;
    case 721:
        return false;
    case 722:
        return true;
    case 723:
        return false;
    case 724:
        return true;
    case 725:
        return false;
    case 726:
        return true;
    case 727:
        return false;
    case 728:
        return true;
    case 729:
        return false;
    case 730:
        return true;
    case 731:
        return false;
    case 732:
        return true;
    case 733:
        return false;
    case 734:
        return true;
    case 735:
        return false;
    case 736:
        return true;
    case 737:
        return false;
    case 738:
        return true;
    case 739:
        return false;
    case 740:
        return true;
    case 741:
        return false;
    case 742:
        return true;
    case 743:
        return false;
    case 744:
        return true;
    case 745:
        return false;
    case 746:
        return true;
    case 747:
        return false;
    case 748:
        return true;
    case 749:
        return false;
    case 750:
        return true;
    case 751:
        return false;
    case 752:
        return true;
    case 753:
        return false;
    case 754:
        return true;
    case 755:
        return false;
    case 756:
        return true;
    case 757:
        return false;
    case 758:
        return true;
    case 759:
        return false;
    case 760:
        return true;
    case 761:
        return false;
    case 762:
        return true;
    case 763:
        return false;
    case 764:
        return true;
    case 765:
        return false;
    case 766:
        return true;
    case 767:
        return false;
    case 768:
        return true;
    case 769:
        return false;
    case 770:
        return true;
    case 771:
        return false;
    case 772:
        return true;
    case 773:
        return false;
    case 774:
        return true;
    case 775:
        return false;
    case 776:
        return true;
    case 777:
        return false;
    case 778:
        return true;
    case 779:
        return false;
    case 780:
        return true;
    case 781:
        return false;
    case 782:
        return true;
    case 783:
        return false;
    case 784:
        return true;
    case 785:
        return false;
    case 786:
        return true;
    case 787:
        return false;
    case 788:
        return true;
    case 789:
        return false;
    case 790:
        return true;
    case 791:
        return false;
    case 792:
        return true;
    case 793:
        return false;
    case 794:
        return true;
    case 795:
        return false;
    case 796:
        return true;
    case 797:
        return false;
    case 798:
        return true;
    case 799:
        return false;
    case 800:
        return true;
    case 801:
        return false;
    case 802:
        return true;
    case 803:
        return false;
    case 804:
        return true;
    case 805:
        return false;
    case 806:
        return true;
    case 807:
        return false;
    case 808:
        return true;
    case 809:
        return false;
    case 810:
        return true;
    case 811:
        return false;
    case 812:
        return true;
    case 813:
        return false;
    case 814:
        return true;
    case 815:
        return false;
    case 816:
        return true;
    case 817:
        return false;
    case 818:
        return true;
    case 819:
        return false;
    case 820:
        return true;
    case 821:
        return false;
    case 822:
        return true;
    case 823:
        return false;
    case 824:
        return true;
    case 825:
        return false;
    case 826:
        return true;
    case 827:
        return false;
    case 828:
        return true;
    case 829:
        return false;
    case 830:
        return true;
    case 831:
        return false;
    case 832:
        return true;
    case 833:
        return false;
    case 834:
        return true;
    case 835:
        return false;
    case 836:
        return true;
    case 837:
        return false;
    case 838:
        return true;
    case 839:
        return false;
    case 840:
        return true;
    case 841:
        return false;
    case 842:
        return true;
    case 843:
        return false;
    case 844:
        return true;
    case 845:
        return false;
    case 846:
        return true;
    case 847:
        return false;
    case 848:
        return true;
    case 849:
        return false;
    case 850:
        return true;
    case 851:
        return false;
    case 852:
        return true;
    case 853:
        return false;
    case 854:
        return true;
    case 855:
        return false;
    case 856:
        return true;
    case 857:
        return false;
    case 858:
        return true;
    case 859:
        return false;
    case 860:
        return true;
    case 861:
        return false;
    case 862:
        return true;
    case 863:
        return false;
    case 864:
        return true;
    case 865:
        return false;
    case 866:
        return true;
    case 867:
        return false;
    case 868:
        return true;
    case 869:
        return false;
    case 870:
        return true;
    case 871:
        return false;
    case 872:
        return true;
    case 873:
        return false;
    case 874:
        return true;
    case 875:
        return false;
    case 876:
        return true;
    case 877:
        return false;
    case 878:
        return true;
    case 879:
        return false;
    case 880:
        return true;
    case 881:
        return false;
    case 882:
        return true;
    case 883:
        return false;
    case 884:
        return true;
    case 885:
        return false;
    case 886:
        return true;
    case 887:
        return false;
    case 888:
        return true;
    case 889:
        return false;
    case 890:
        return true;
    case 891:
        return false;
    case 892:
        return true;
    case 893:
        return false;
    case 894:
        return true;
    case 895:
        return false;
    case 896:
        return true;
    case 897:
        return false;
    case 898:
        return true;
    case 899:
        return false;
    case 900:
        return true;
    case 901:
        return false;
    case 902:
        return true;
    case 903:
        return false;
    case 904:
        return true;
    case 905:
        return false;
    case 906:
        return true;
    case 907:
        return false;
    case 908:
        return true;
    case 909:
        return false;
    case 910:
        return true;
    case 911:
        return false;
    case 912:
        return true;
    case 913:
        return false;
    case 914:
        return true;
    case 915:
        return false;
    case 916:
        return true;
    case 917:
        return false;
    case 918:
        return true;
    case 919:
        return false;
    case 920:
        return true;
    case 921:
        return false;
    case 922:
        return true;
    case 923:
        return false;
    case 924:
        return true;
    case 925:
        return false;
    case 926:
        return true;
    case 927:
        return false;
    case 928:
        return true;
    case 929:
        return false;
    case 930:
        return true;
    case 931:
        return false;
    case 932:
        return true;
    case 933:
        return false;
    case 934:
        return true;
    case 935:
        return false;
    case 936:
        return true;
    case 937:
        return false;
    case 938:
        return true;
    case 939:
        return false;
    case 940:
        return true;
    case 941:
        return false;
    case 942:
        return true;
    case 943:
        return false;
    case 944:
        return true;
    case 945:
        return false;
    case 946:
        return true;
    case 947:
        return false;
    case 948:
        return true;
    case 949:
        return false;
    case 950:
        return true;
    case 951:
        return false;
    case 952:
        return true;
    case 953:
        return false;
    case 954:
        return true;
    case 955:
        return false;
    case 956:
        return true;
    case 957:
        return false;
    case 958:
        return true;
    case 959:
        return false;
    case 960:
        return true;
    case 961:
        return false;
    case 962:
        return true;
    case 963:
        return false;
    case 964:
        return true;
    case 965:
        return false;
    case 966:
        return true;
    case 967:
        return false;
    case 968:
        return true;
    case 969:
        return false;
    case 970:
        return true;
    case 971:
        return false;
    case 972:
        return true;
    case 973:
        return false;
    case 974:
        return true;
    case 975:
        return false;
    case 976:
        return true;
    case 977:
        return false;
    case 978:
        return true;
    case 979:
        return false;
    case 980:
        return true;
    case 981:
        return false;
    case 982:
        return true;
    case 983:
        return false;
    case 984:
        return true;
    case 985:
        return false;
    case 986:
        return true;
    case 987:
        return false;
    case 988:
        return true;
    case 989:
        return false;
    case 990:
        return true;
    case 991:
        return false;
    case 992:
        return true;
    case 993:
        return false;
    case 994:
        return true;
    case 995:
        return false;
    case 996:
        return true;
    case 997:
        return false;
    case 998:
        return true;
    case 999:
        return false;
    case 1000:
        return true;
    case 1001:
        return false;
    case 1002:
        return true;
    case 1003:
        return false;
    case 1004:
        return true;
    case 1005:
        return false;
    case 1006:
        return true;
    case 1007:
        return false;
    case 1008:
        return true;
    case 1009:
        return false;
    case 1010:
        return true;
    case 1011:
        return false;
    case 1012:
        return true;
    case 1013:
        return false;
    case 1014:
        return true;
    case 1015:
        return false;
    case 1016:
        return true;
    case 1017:
        return false;
    case 1018:
        return true;
    case 1019:
        return false;
    case 1020:
        return true;
    case 1021:
        return false;
    case 1022:
        return true;
    case 1023:
        return false;
    case 1024:
        return true;
    case 1025:
        return false;
    case 1026:
        return true;
    case 1027:
        return false;
    case 1028:
        return true;
    case 1029:
        return false;
    case 1030:
        return true;
    case 1031:
        return false;
    case 1032:
        return true;
    case 1033:
        return false;
    case 1034:
        return true;
    case 1035:
        return false;
    case 1036:
        return true;
    case 1037:
        return false;
    case 1038:
        return true;
    case 1039:
        return false;
    case 1040:
        return true;
    case 1041:
        return false;
    case 1042:
        return true;
    case 1043:
        return false;
    case 1044:
        return true;
    case 1045:
        return false;
    case 1046:
        return true;
    case 1047:
        return false;
    case 1048:
        return true;
    case 1049:
        return false;
    case 1050:
        return true;
    case 1051:
        return false;
    case 1052:
        return true;
    case 1053:
        return false;
    case 1054:
        return true;
    case 1055:
        return false;
    case 1056:
        return true;
    case 1057:
        return false;
    case 1058:
        return true;
    case 1059:
        return false;
    case 1060:
        return true;
    case 1061:
        return false;
    case 1062:
        return true;
    case 1063:
        return false;
    case 1064:
        return true;
    case 1065:
        return false;
    case 1066:
        return true;
    case 1067:
        return false;
    case 1068:
        return true;
    case 1069:
        return false;
    case 1070:
        return true;
    case 1071:
        return false;
    case 1072:
        return true;
    case 1073:
        return false;
    case 1074:
        return true;
    case 1075:
        return false;
    case 1076:
        return true;
    case 1077:
        return false;
    case 1078:
        return true;
    case 1079:
        return false;
    case 1080:
        return true;
    case 1081:
        return false;
    case 1082:
        return true;
    case 1083:
        return false;
    case 1084:
        return true;
    case 1085:
        return false;
    case 1086:
        return true;
    case 1087:
        return false;
    case 1088:
        return true;
    case 1089:
        return false;
    case 1090:
        return true;
    case 1091:
        return false;
    case 1092:
        return true;
    case 1093:
        return false;
    case 1094:
        return true;
    case 1095:
        return false;
    case 1096:
        return true;
    case 1097:
        return false;
    case 1098:
        return true;
    case 1099:
        return false;
    case 1100:
        return true;
    case 1101:
        return false;
    case 1102:
        return true;
    case 1103:
        return false;
    case 1104:
        return true;
    case 1105:
        return false;
    case 1106:
        return true;
    case 1107:
        return false;
    case 1108:
        return true;
    case 1109:
        return false;
    case 1110:
        return true;
    case 1111:
        return false;
    case 1112:
        return true;
    case 1113:
        return false;
    case 1114:
        return true;
    case 1115:
        return false;
    case 1116:
        return true;
    case 1117:
        return false;
    case 1118:
        return true;
    case 1119:
        return false;
    case 1120:
        return true;
    case 1121:
        return false;
    case 1122:
        return true;
    case 1123:
        return false;
    case 1124:
        return true;
    case 1125:
        return false;
    case 1126:
        return true;
    case 1127:
        return false;
    case 1128:
        return true;
    case 1129:
        return false;
    case 1130:
        return true;
    case 1131:
        return false;
    case 1132:
        return true;
    case 1133:
        return false;
    case 1134:
        return true;
    case 1135:
        return false;
    case 1136:
        return true;
    case 1137:
        return false;
    case 1138:
        return true;
    case 1139:
        return false;
    case 1140:
        return true;
    case 1141:
        return false;
    case 1142:
        return true;
    case 1143:
        return false;
    case 1144:
        return true;
    case 1145:
        return false;
    case 1146:
        return true;
    case 1147:
        return false;
    case 1148:
        return true;
    case 1149:
        return false;
    case 1150:
        return true;
    case 1151:
        return false;
    case 1152:
        return true;
    case 1153:
        return false;
    case 1154:
        return true;
    case 1155:
        return false;
    case 1156:
        return true;
    case 1157:
        return false;
    case 1158:
        return true;
    case 1159:
        return false;
    case 1160:
        return true;
    case 1161:
        return false;
    case 1162:
        return true;
    case 1163:
        return false;
    case 1164:
        return true;
    case 1165:
        return false;
    case 1166:
        return true;
    case 1167:
        return false;
    case 1168:
        return true;
    case 1169:
        return false;
    case 1170:
        return true;
    case 1171:
        return false;
    case 1172:
        return true;
    case 1173:
        return false;
    case 1174:
        return true;
    case 1175:
        return false;
    case 1176:
        return true;
    case 1177:
        return false;
    case 1178:
        return true;
    case 1179:
        return false;
    case 1180:
        return true;
    case 1181:
        return false;
    case 1182:
        return true;
    case 1183:
        return false;
    case 1184:
        return true;
    case 1185:
        return false;
    case 1186:
        return true;
    case 1187:
        return false;
    case 1188:
        return true;
    case 1189:
        return false;
    case 1190:
        return true;
    case 1191:
        return false;
    case 1192:
        return true;
    case 1193:
        return false;
    case 1194:
        return true;
    case 1195:
        return false;
    case 1196:
        return true;
    case 1197:
        return false;
    case 1198:
        return true;
    case 1199:
        return false;
    case 1200:
        return true;
    case 1201:
        return false;
    case 1202:
        return true;
    case 1203:
        return false;
    case 1204:
        return true;
    case 1205:
        return false;
    case 1206:
        return true;
    case 1207:
        return false;
    case 1208:
        return true;
    case 1209:
        return false;
    case 1210:
        return true;
    case 1211:
        return false;
    case 1212:
        return true;
    case 1213:
        return false;
    case 1214:
        return true;
    case 1215:
        return false;
    case 1216:
        return true;
    case 1217:
        return false;
    case 1218:
        return true;
    case 1219:
        return false;
    case 1220:
        return true;
    case 1221:
        return false;
    case 1222:
        return true;
    case 1223:
        return false;
    case 1224:
        return true;
    case 1225:
        return false;
    case 1226:
        return true;
    case 1227:
        return false;
    case 1228:
        return true;
    case 1229:
        return false;
    case 1230:
        return true;
    case 1231:
        return false;
    case 1232:
        return true;
    case 1233:
        return false;
    case 1234:
        return true;
    case 1235:
        return false;
    case 1236:
        return true;
    case 1237:
        return false;
    case 1238:
        return true;
    case 1239:
        return false;
    case 1240:
        return true;
    case 1241:
        return false;
    case 1242:
        return true;
    case 1243:
        return false;
    case 1244:
        return true;
    case 1245:
        return false;
    case 1246:
        return true;
    case 1247:
        return false;
    case 1248:
        return true;
    case 1249:
        return false;
    case 1250:
        return true;
    case 1251:
        return false;
    case 1252:
        return true;
    case 1253:
        return false;
    case 1254:
        return true;
    case 1255:
        return false;
    case 1256:
        return true;
    case 1257:
        return false;
    case 1258:
        return true;
    case 1259:
        return false;
    case 1260:
        return true;
    case 1261:
        return false;
    case 1262:
        return true;
    case 1263:
        return false;
    case 1264:
        return true;
    case 1265:
        return false;
    case 1266:
        return true;
    case 1267:
        return false;
    case 1268:
        return true;
    case 1269:
        return false;
    case 1270:
        return true;
    case 1271:
        return false;
    case 1272:
        return true;
    case 1273:
        return false;
    case 1274:
        return true;
    case 1275:
        return false;
    case 1276:
        return true;
    case 1277:
        return false;
    case 1278:
        return true;
    case 1279:
        return false;
    case 1280:
        return true;
    case 1281:
        return false;
    case 1282:
        return true;
    case 1283:
        return false;
    case 1284:
        return true;
    case 1285:
        return false;
    case 1286:
        return true;
    case 1287:
        return false;
    case 1288:
        return true;
    case 1289:
        return false;
    case 1290:
        return true;
    case 1291:
        return false;
    case 1292:
        return true;
    case 1293:
        return false;
    case 1294:
        return true;
    case 1295:
        return false;
    case 1296:
        return true;
    case 1297:
        return false;
    case 1298:
        return true;
    case 1299:
        return false;
    case 1300:
        return true;
    case 1301:
        return false;
    case 1302:
        return true;
    case 1303:
        return false;
    case 1304:
        return true;
    case 1305:
        return false;
    case 1306:
        return true;
    case 1307:
        return false;
    case 1308:
        return true;
    case 1309:
        return false;
    case 1310:
        return true;
    case 1311:
        return false;
    case 1312:
        return true;
    case 1313:
        return false;
    case 1314:
        return true;
    case 1315:
        return false;
    case 1316:
        return true;
    case 1317:
        return false;
    case 1318:
        return true;
    case 1319:
        return false;
    case 1320:
        return true;
    case 1321:
        return false;
    case 1322:
        return true;
    case 1323:
        return false;
    case 1324:
        return true;
    case 1325:
        return false;
    case 1326:
        return true;
    case 1327:
        return false;
    case 1328:
        return true;
    case 1329:
        return false;
    case 1330:
        return true;
    case 1331:
        return false;
    case 1332:
        return true;
    case 1333:
        return false;
    case 1334:
        return true;
    case 1335:
        return false;
    case 1336:
        return true;
    case 1337:
        return false;
    case 1338:
        return true;
    case 1339:
        return false;
    case 1340:
        return true;
    case 1341:
        return false;
    case 1342:
        return true;
    case 1343:
        return false;
    case 1344:
        return true;
    case 1345:
        return false;
    case 1346:
        return true;
    case 1347:
        return false;
    case 1348:
        return true;
    case 1349:
        return false;
    case 1350:
        return true;
    case 1351:
        return false;
    case 1352:
        return true;
    case 1353:
        return false;
    case 1354:
        return true;
    case 1355:
        return false;
    case 1356:
        return true;
    case 1357:
        return false;
    case 1358:
        return true;
    case 1359:
        return false;
    case 1360:
        return true;
    case 1361:
        return false;
    case 1362:
        return true;
    case 1363:
        return false;
    case 1364:
        return true;
    case 1365:
        return false;
    case 1366:
        return true;
    case 1367:
        return false;
    case 1368:
        return true;
    case 1369:
        return false;
    case 1370:
        return true;
    case 1371:
        return false;
    case 1372:
        return true;
    case 1373:
        return false;
    case 1374:
        return true;
    case 1375:
        return false;
    case 1376:
        return true;
    case 1377:
        return false;
    case 1378:
        return true;
    case 1379:
        return false;
    case 1380:
        return true;
    case 1381:
        return false;
    case 1382:
        return true;
    case 1383:
        return false;
    case 1384:
        return true;
    case 1385:
        return false;
    case 1386:
        return true;
    case 1387:
        return false;
    case 1388:
        return true;
    case 1389:
        return false;
    case 1390:
        return true;
    case 1391:
        return false;
    case 1392:
        return true;
    case 1393:
        return false;
    case 1394:
        return true;
    case 1395:
        return false;
    case 1396:
        return true;
    case 1397:
        return false;
    case 1398:
        return true;
    case 1399:
        return false;
    case 1400:
        return true;
    case 1401:
        return false;
    case 1402:
        return true;
    case 1403:
        return false;
    case 1404:
        return true;
    case 1405:
        return false;
    case 1406:
        return true;
    case 1407:
        return false;
    case 1408:
        return true;
    case 1409:
        return false;
    case 1410:
        return true;
    case 1411:
        return false;
    case 1412:
        return true;
    case 1413:
        return false;
    case 1414:
        return true;
    case 1415:
        return false;
    case 1416:
        return true;
    case 1417:
        return false;
    case 1418:
        return true;
    case 1419:
        return false;
    case 1420:
        return true;
    case 1421:
        return false;
    case 1422:
        return true;
    case 1423:
        return false;
    case 1424:
        return true;
    case 1425:
        return false;
    case 1426:
        return true;
    case 1427:
        return false;
    case 1428:
        return true;
    case 1429:
        return false;
    case 1430:
        return true;
    case 1431:
        return false;
    case 1432:
        return true;
    case 1433:
        return false;
    case 1434:
        return true;
    case 1435:
        return false;
    case 1436:
        return true;
    case 1437:
        return false;
    case 1438:
        return true;
    case 1439:
        return false;
    case 1440:
        return true;
    case 1441:
        return false;
    case 1442:
        return true;
    case 1443:
        return false;
    case 1444:
        return true;
    case 1445:
        return false;
    case 1446:
        return true;
    case 1447:
        return false;
    case 1448:
        return true;
    case 1449:
        return false;
    case 1450:
        return true;
    case 1451:
        return false;
    case 1452:
        return true;
    case 1453:
        return false;
    case 1454:
        return true;
    case 1455:
        return false;
    case 1456:
        return true;
    case 1457:
        return false;
    case 1458:
        return true;
    case 1459:
        return false;
    case 1460:
        return true;
    case 1461:
        return false;
    case 1462:
        return true;
    case 1463:
        return false;
    case 1464:
        return true;
    case 1465:
        return false;
    case 1466:
        return true;
    case 1467:
        return false;
    case 1468:
        return true;
    case 1469:
        return false;
    case 1470:
        return true;
    case 1471:
        return false;
    case 1472:
        return true;
    case 1473:
        return false;
    case 1474:
        return true;
    case 1475:
        return false;
    case 1476:
        return true;
    case 1477:
        return false;
    case 1478:
        return true;
    case 1479:
        return false;
    case 1480:
        return true;
    case 1481:
        return false;
    case 1482:
        return true;
    case 1483:
        return false;
    case 1484:
        return true;
    case 1485:
        return false;
    case 1486:
        return true;
    case 1487:
        return false;
    case 1488:
        return true;
    case 1489:
        return false;
    case 1490:
        return true;
    case 1491:
        return false;
    case 1492:
        return true;
    case 1493:
        return false;
    case 1494:
        return true;
    case 1495:
        return false;
    case 1496:
        return true;
    case 1497:
        return false;
    case 1498:
        return true;
    case 1499:
        return false;
    case 1500:
        return true;
    case 1501:
        return false;
    case 1502:
        return true;
    case 1503:
        return false;
    case 1504:
        return true;
    case 1505:
        return false;
    case 1506:
        return true;
    case 1507:
        return false;
    case 1508:
        return true;
    case 1509:
        return false;
    case 1510:
        return true;
    case 1511:
        return false;
    case 1512:
        return true;
    case 1513:
        return false;
    case 1514:
        return true;
    case 1515:
        return false;
    case 1516:
        return true;
    case 1517:
        return false;
    case 1518:
        return true;
    case 1519:
        return false;
    case 1520:
        return true;
    case 1521:
        return false;
    case 1522:
        return true;
    case 1523:
        return false;
    case 1524:
        return true;
    case 1525:
        return false;
    case 1526:
        return true;
    case 1527:
        return false;
    case 1528:
        return true;
    case 1529:
        return false;
    case 1530:
        return true;
    case 1531:
        return false;
    case 1532:
        return true;
    case 1533:
        return false;
    case 1534:
        return true;
    case 1535:
        return false;
    case 1536:
        return true;
    case 1537:
        return false;
    case 1538:
        return true;
    case 1539:
        return false;
    case 1540:
        return true;
    case 1541:
        return false;
    case 1542:
        return true;
    case 1543:
        return false;
    case 1544:
        return true;
    case 1545:
        return false;
    case 1546:
        return true;
    case 1547:
        return false;
    case 1548:
        return true;
    case 1549:
        return false;
    case 1550:
        return true;
    case 1551:
        return false;
    case 1552:
        return true;
    case 1553:
        return false;
    case 1554:
        return true;
    case 1555:
        return false;
    case 1556:
        return true;
    case 1557:
        return false;
    case 1558:
        return true;
    case 1559:
        return false;
    case 1560:
        return true;
    case 1561:
        return false;
    case 1562:
        return true;
    case 1563:
        return false;
    case 1564:
        return true;
    case 1565:
        return false;
    case 1566:
        return true;
    case 1567:
        return false;
    case 1568:
        return true;
    case 1569:
        return false;
    case 1570:
        return true;
    case 1571:
        return false;
    case 1572:
        return true;
    case 1573:
        return false;
    case 1574:
        return true;
    case 1575:
        return false;
    case 1576:
        return true;
    case 1577:
        return false;
    case 1578:
        return true;
    case 1579:
        return false;
    case 1580:
        return true;
    case 1581:
        return false;
    case 1582:
        return true;
    case 1583:
        return false;
    case 1584:
        return true;
    case 1585:
        return false;
    case 1586:
        return true;
    case 1587:
        return false;
    case 1588:
        return true;
    case 1589:
        return false;
    case 1590:
        return true;
    case 1591:
        return false;
    case 1592:
        return true;
    case 1593:
        return false;
    case 1594:
        return true;
    case 1595:
        return false;
    case 1596:
        return true;
    case 1597:
        return false;
    case 1598:
        return true;
    case 1599:
        return false;
    case 1600:
        return true;
    case 1601:
        return false;
    case 1602:
        return true;
    case 1603:
        return false;
    case 1604:
        return true;
    case 1605:
        return false;
    case 1606:
        return true;
    case 1607:
        return false;
    case 1608:
        return true;
    case 1609:
        return false;
    case 1610:
        return true;
    case 1611:
        return false;
    case 1612:
        return true;
    case 1613:
        return false;
    case 1614:
        return true;
    case 1615:
        return false;
    case 1616:
        return true;
    case 1617:
        return false;
    case 1618:
        return true;
    case 1619:
        return false;
    case 1620:
        return true;
    case 1621:
        return false;
    case 1622:
        return true;
    case 1623:
        return false;
    case 1624:
        return true;
    case 1625:
        return false;
    case 1626:
        return true;
    case 1627:
        return false;
    case 1628:
        return true;
    case 1629:
        return false;
    case 1630:
        return true;
    case 1631:
        return false;
    case 1632:
        return true;
    case 1633:
        return false;
    case 1634:
        return true;
    case 1635:
        return false;
    case 1636:
        return true;
    case 1637:
        return false;
    case 1638:
        return true;
    case 1639:
        return false;
    case 1640:
        return true;
    case 1641:
        return false;
    case 1642:
        return true;
    case 1643:
        return false;
    case 1644:
        return true;
    case 1645:
        return false;
    case 1646:
        return true;
    case 1647:
        return false;
    case 1648:
        return true;
    case 1649:
        return false;
    case 1650:
        return true;
    case 1651:
        return false;
    case 1652:
        return true;
    case 1653:
        return false;
    case 1654:
        return true;
    case 1655:
        return false;
    case 1656:
        return true;
    case 1657:
        return false;
    case 1658:
        return true;
    case 1659:
        return false;
    case 1660:
        return true;
    case 1661:
        return false;
    case 1662:
        return true;
    case 1663:
        return false;
    case 1664:
        return true;
    case 1665:
        return false;
    case 1666:
        return true;
    case 1667:
        return false;
    case 1668:
        return true;
    case 1669:
        return false;
    case 1670:
        return true;
    case 1671:
        return false;
    case 1672:
        return true;
    case 1673:
        return false;
    case 1674:
        return true;
    case 1675:
        return false;
    case 1676:
        return true;
    case 1677:
        return false;
    case 1678:
        return true;
    case 1679:
        return false;
    case 1680:
        return true;
    case 1681:
        return false;
    case 1682:
        return true;
    case 1683:
        return false;
    case 1684:
        return true;
    case 1685:
        return false;
    case 1686:
        return true;
    case 1687:
        return false;
    case 1688:
        return true;
    case 1689:
        return false;
    case 1690:
        return true;
    case 1691:
        return false;
    case 1692:
        return true;
    case 1693:
        return false;
    case 1694:
        return true;
    case 1695:
        return false;
    case 1696:
        return true;
    case 1697:
        return false;
    case 1698:
        return true;
    case 1699:
        return false;
    case 1700:
        return true;
    case 1701:
        return false;
    case 1702:
        return true;
    case 1703:
        return false;
    case 1704:
        return true;
    case 1705:
        return false;
    case 1706:
        return true;
    case 1707:
        return false;
    case 1708:
        return true;
    case 1709:
        return false;
    case 1710:
        return true;
    case 1711:
        return false;
    case 1712:
        return true;
    case 1713:
        return false;
    case 1714:
        return true;
    case 1715:
        return false;
    case 1716:
        return true;
    case 1717:
        return false;
    case 1718:
        return true;
    case 1719:
        return false;
    case 1720:
        return true;
    case 1721:
        return false;
    case 1722:
        return true;
    case 1723:
        return false;
    case 1724:
        return true;
    case 1725:
        return false;
    case 1726:
        return true;
    case 1727:
        return false;
    case 1728:
        return true;
    case 1729:
        return false;
    case 1730:
        return true;
    case 1731:
        return false;
    case 1732:
        return true;
    case 1733:
        return false;
    case 1734:
        return true;
    case 1735:
        return false;
    case 1736:
        return true;
    case 1737:
        return false;
    case 1738:
        return true;
    case 1739:
        return false;
    case 1740:
        return true;
    case 1741:
        return false;
    case 1742:
        return true;
    case 1743:
        return false;
    case 1744:
        return true;
    case 1745:
        return false;
    case 1746:
        return true;
    case 1747:
        return false;
    case 1748:
        return true;
    case 1749:
        return false;
    case 1750:
        return true;
    case 1751:
        return false;
    case 1752:
        return true;
    case 1753:
        return false;
    case 1754:
        return true;
    case 1755:
        return false;
    case 1756:
        return true;
    case 1757:
        return false;
    case 1758:
        return true;
    case 1759:
        return false;
    case 1760:
        return true;
    case 1761:
        return false;
    case 1762:
        return true;
    case 1763:
        return false;
    case 1764:
        return true;
    case 1765:
        return false;
    case 1766:
        return true;
    case 1767:
        return false;
    case 1768:
        return true;
    case 1769:
        return false;
    case 1770:
        return true;
    case 1771:
        return false;
    case 1772:
        return true;
    case 1773:
        return false;
    case 1774:
        return true;
    case 1775:
        return false;
    case 1776:
        return true;
    case 1777:
        return false;
    case 1778:
        return true;
    case 1779:
        return false;
    case 1780:
        return true;
    case 1781:
        return false;
    case 1782:
        return true;
    case 1783:
        return false;
    case 1784:
        return true;
    case 1785:
        return false;
    case 1786:
        return true;
    case 1787:
        return false;
    case 1788:
        return true;
    case 1789:
        return false;
    case 1790:
        return true;
    case 1791:
        return false;
    case 1792:
        return true;
    case 1793:
        return false;
    case 1794:
        return true;
    case 1795:
        return false;
    case 1796:
        return true;
    case 1797:
        return false;
    case 1798:
        return true;
    case 1799:
        return false;
    case 1800:
        return true;
    case 1801:
        return false;
    case 1802:
        return true;
    case 1803:
        return false;
    case 1804:
        return true;
    case 1805:
        return false;
    case 1806:
        return true;
    case 1807:
        return false;
    case 1808:
        return true;
    case 1809:
        return false;
    case 1810:
        return true;
    case 1811:
        return false;
    case 1812:
        return true;
    case 1813:
        return false;
    case 1814:
        return true;
    case 1815:
        return false;
    case 1816:
        return true;
    case 1817:
        return false;
    case 1818:
        return true;
    case 1819:
        return false;
    case 1820:
        return true;
    case 1821:
        return false;
    case 1822:
        return true;
    case 1823:
        return false;
    case 1824:
        return true;
    case 1825:
        return false;
    case 1826:
        return true;
    case 1827:
        return false;
    case 1828:
        return true;
    case 1829:
        return false;
    case 1830:
        return true;
    case 1831:
        return false;
    case 1832:
        return true;
    case 1833:
        return false;
    case 1834:
        return true;
    case 1835:
        return false;
    case 1836:
        return true;
    case 1837:
        return false;
    case 1838:
        return true;
    case 1839:
        return false;
    case 1840:
        return true;
    case 1841:
        return false;
    case 1842:
        return true;
    case 1843:
        return false;
    case 1844:
        return true;
    case 1845:
        return false;
    case 1846:
        return true;
    case 1847:
        return false;
    case 1848:
        return true;
    case 1849:
        return false;
    case 1850:
        return true;
    case 1851:
        return false;
    case 1852:
        return true;
    case 1853:
        return false;
    case 1854:
        return true;
    case 1855:
        return false;
    case 1856:
        return true;
    case 1857:
        return false;
    case 1858:
        return true;
    case 1859:
        return false;
    case 1860:
        return true;
    case 1861:
        return false;
    case 1862:
        return true;
    case 1863:
        return false;
    case 1864:
        return true;
    case 1865:
        return false;
    case 1866:
        return true;
    case 1867:
        return false;
    case 1868:
        return true;
    case 1869:
        return false;
    case 1870:
        return true;
    case 1871:
        return false;
    case 1872:
        return true;
    case 1873:
        return false;
    case 1874:
        return true;
    case 1875:
        return false;
    case 1876:
        return true;
    case 1877:
        return false;
    case 1878:
        return true;
    case 1879:
        return false;
    case 1880:
        return true;
    case 1881:
        return false;
    case 1882:
        return true;
    case 1883:
        return false;
    case 1884:
        return true;
    case 1885:
        return false;
    case 1886:
        return true;
    case 1887:
        return false;
    case 1888:
        return true;
    case 1889:
        return false;
    case 1890:
        return true;
    case 1891:
        return false;
    case 1892:
        return true;
    case 1893:
        return false;
    case 1894:
        return true;
    case 1895:
        return false;
    case 1896:
        return true;
    case 1897:
        return false;
    case 1898:
        return true;
    case 1899:
        return false;
    case 1900:
        return true;
    case 1901:
        return false;
    case 1902:
        return true;
    case 1903:
        return false;
    case 1904:
        return true;
    case 1905:
        return false;
    case 1906:
        return true;
    case 1907:
        return false;
    case 1908:
        return true;
    case 1909:
        return false;
    case 1910:
        return true;
    case 1911:
        return false;
    case 1912:
        return true;
    case 1913:
        return false;
    case 1914:
        return true;
    case 1915:
        return false;
    case 1916:
        return true;
    case 1917:
        return false;
    case 1918:
        return true;
    case 1919:
        return false;
    case 1920:
        return true;
    case 1921:
        return false;
    case 1922:
        return true;
    case 1923:
        return false;
    case 1924:
        return true;
    case 1925:
        return false;
    case 1926:
        return true;
    case 1927:
        return false;
    case 1928:
        return true;
    case 1929:
        return false;
    case 1930:
        return true;
    case 1931:
        return false;
    case 1932:
        return true;
    case 1933:
        return false;
    case 1934:
        return true;
    case 1935:
        return false;
    case 1936:
        return true;
    case 1937:
        return false;
    case 1938:
        return true;
    case 1939:
        return false;
    case 1940:
        return true;
    case 1941:
        return false;
    case 1942:
        return true;
    case 1943:
        return false;
    case 1944:
        return true;
    case 1945:
        return false;
    case 1946:
        return true;
    case 1947:
        return false;
    case 1948:
        return true;
    case 1949:
        return false;
    case 1950:
        return true;
    case 1951:
        return false;
    case 1952:
        return true;
    case 1953:
        return false;
    case 1954:
        return true;
    case 1955:
        return false;
    case 1956:
        return true;
    case 1957:
        return false;
    case 1958:
        return true;
    case 1959:
        return false;
    case 1960:
        return true;
    case 1961:
        return false;
    case 1962:
        return true;
    case 1963:
        return false;
    case 1964:
        return true;
    case 1965:
        return false;
    case 1966:
        return true;
    case 1967:
        return false;
    case 1968:
        return true;
    case 1969:
        return false;
    case 1970:
        return true;
    case 1971:
        return false;
    case 1972:
        return true;
    case 1973:
        return false;
    case 1974:
        return true;
    case 1975:
        return false;
    case 1976:
        return true;
    case 1977:
        return false;
    case 1978:
        return true;
    case 1979:
        return false;
    case 1980:
        return true;
    case 1981:
        return false;
    case 1982:
        return true;
    case 1983:
        return false;
    case 1984:
        return true;
    case 1985:
        return false;
    case 1986:
        return true;
    case 1987:
        return false;
    case 1988:
        return true;
    case 1989:
        return false;
    case 1990:
        return true;
    case 1991:
        return false;
    case 1992:
        return true;
    case 1993:
        return false;
    case 1994:
        return true;
    case 1995:
        return false;
    case 1996:
        return true;
    case 1997:
        return false;
    case 1998:
        return true;
    case 1999:
        return false;
    case 2000:
        return true;
    case 2001:
        return false;
    case 2002:
        return true;
    case 2003:
        return false;
    case 2004:
        return true;
    case 2005:
        return false;
    case 2006:
        return true;
    case 2007:
        return false;
    case 2008:
        return true;
    case 2009:
        return false;
    case 2010:
        return true;
    case 2011:
        return false;
    case 2012:
        return true;
    case 2013:
        return false;
    case 2014:
        return true;
    case 2015:
        return false;
    case 2016:
        return true;
    case 2017:
        return false;
    case 2018:
        return true;
    case 2019:
        return false;
    case 2020:
        return true;
    case 2021:
        return false;
    case 2022:
        return true;
    case 2023:
        return false;
    case 2024:
        return true;
    case 2025:
        return false;
    case 2026:
        return true;
    case 2027:
        return false;
    case 2028:
        return true;
    case 2029:
        return false;
    case 2030:
        return true;
    case 2031:
        return false;
    case 2032:
        return true;
    case 2033:
        return false;
    case 2034:
        return true;
    case 2035:
        return false;
    case 2036:
        return true;
    case 2037:
        return false;
    case 2038:
        return true;
    case 2039:
        return false;
    case 2040:
        return true;
    case 2041:
        return false;
    case 2042:
        return true;
    case 2043:
        return false;
    case 2044:
        return true;
    case 2045:
        return false;
    case 2046:
        return true;
    case 2047:
        return false;
    case 2048:
        return true;
    case 2049:
        return false;
    case 2050:
        return true;
    case 2051:
        return false;
    case 2052:
        return true;
    case 2053:
        return false;
    case 2054:
        return true;
    case 2055:
        return false;
    case 2056:
        return true;
    case 2057:
        return false;
    case 2058:
        return true;
    case 2059:
        return false;
    case 2060:
        return true;
    case 2061:
        return false;
    case 2062:
        return true;
    case 2063:
        return false;
    case 2064:
        return true;
    case 2065:
        return false;
    case 2066:
        return true;
    case 2067:
        return false;
    case 2068:
        return true;
    case 2069:
        return false;
    case 2070:
        return true;
    case 2071:
        return false;
    case 2072:
        return true;
    case 2073:
        return false;
    case 2074:
        return true;
    case 2075:
        return false;
    case 2076:
        return true;
    case 2077:
        return false;
    case 2078:
        return true;
    case 2079:
        return false;
    case 2080:
        return true;
    case 2081:
        return false;
    case 2082:
        return true;
    case 2083:
        return false;
    case 2084:
        return true;
    case 2085:
        return false;
    case 2086:
        return true;
    case 2087:
        return false;
    case 2088:
        return true;
    case 2089:
        return false;
    case 2090:
        return true;
    case 2091:
        return false;
    case 2092:
        return true;
    case 2093:
        return false;
    case 2094:
        return true;
    case 2095:
        return false;
    case 2096:
        return true;
    case 2097:
        return false;
    case 2098:
        return true;
    case 2099:
        return false;
    case 2100:
        return true;
    case 2101:
        return false;
    case 2102:
        return true;
    case 2103:
        return false;
    case 2104:
        return true;
    case 2105:
        return false;
    case 2106:
        return true;
    case 2107:
        return false;
    case 2108:
        return true;
    case 2109:
        return false;
    case 2110:
        return true;
    case 2111:
        return false;
    case 2112:
        return true;
    case 2113:
        return false;
    case 2114:
        return true;
    case 2115:
        return false;
    case 2116:
        return true;
    case 2117:
        return false;
    case 2118:
        return true;
    case 2119:
        return false;
    default:
        return (x&1) == 0;
    }
}